name: Deploy Contoso University Core Demo

on:
  workflow_run:
    workflows: ["Pack Contoso_University_Core"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    environment: dev-demo
    steps:
      -uses: dawidd6/action-download-artifact@v2
        with: 
          workflow: pack-contoso-university-core-demo.yml
          name: packed-solution
      -uses: microsoft/powerplatforms-actions/pack-solution@v1.2.0
        with:
          environment-url: orga7ac6013.crm.dynamics.com
          app-id: ${{ secrets.Appid}}
          client-secret: ${{ secrets.secret}}
          tenant-id: ${{ secrets.tenantid}}
          solution-file: contoso-university-core-managed.zip

