name: Deploy Contoso University Core Demo

on:
  workflow_run:
    workflows: ["Pack Contoso_University_Core"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    environment: production
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with: 
          workflow: pack-solution.yml
          name: packed-solution
      - name: Install Power Platform Tool
        uses: microsoft/powerplatform-actions/actions-install@v1.2.0
      - name: Import Contoso_university Core
        uses: microsoft/powerplatform-actions/import-solution@v1.2.0
        with:
          environment-url: https://orga7ac6013.crm.dynamics.com
          app-id: ${{ secrets.Appid }}
          client-secret: ${{ secrets.secret }}
          tenant-id: ${{ secrets.tenantid }}
          solution-file: contoso-university-core-managed.zip

